In [4]:
import numpy as np
a=np.array([1,2,3,])
print (a) 

[1 2 3]


In [10]:
a=np.array([[1,2,3,],[2,4,5]])
print (a) 

[[1 2 3]
 [2 4 5]]


In [20]:
a=np.array([[[1,2,3],[2,4,5]],[[1,3,8],[2,5,6]]])
print (a)

[[[1 2 3]
  [2 4 5]]

 [[1 3 8]
  [2 5 6]]]


In [21]:
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [24]:
print(arr.shape)

(5,)


In [25]:
print(arr.ndim)

1


In [27]:
print(arr.size)

5


In [28]:
print(arr.dtype)

float64
