In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [2]:
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


In [4]:
arr=np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [5]:
print(np.mean(arr))

30.0


In [3]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.min(arr))
print(np.max(arr))

10
50


In [4]:
print(np.std(arr))

14.142135623730951


In [2]:
import numpy as np
d=np.array([1,2,3,4,5,6,7,8,9,10])
print(d.size)
print(d.shape)
print(d.dtype)

10
(10,)
int64
